# Generated by Django 4.2.3 on 2023-07-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_name_order_customer_order_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
