# Generated by Django 4.2.3 on 2023-07-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_order_price_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
